export const LAY_THONG_TIN_VI_TRI = "LAY_THONG_TIN_VI_TRI";
export const LAY_THONG_TIN_PHONG = "LAY_THONG_TIN_PHONG";
export const LAY_THONG_TIN_DANH_GIA_PHONG = "LAY_THONG_TIN_DANH_GIA_PHONG";
export const SET_REGISTER_INFO = "SET_REGISTER_INFO";
export const SET_USER_INFO = "SET_USER_INFO";
